name: alexa
version: "1.0"
summary: Amazon Alexa snap
description: Add Amazon Alexa to your device
confinement: strict

apps:
  alexa:
    command: bin/alexa.py
    daemon: simple
    plugs: [network, network-bind, alsa, pulseaudio]
  alexa-run:
    command: bin/alexa.py
    plugs: [network, network-bind, alsa, pulseaudio]

parts:
  python-hyper:
    plugin: python
    python-version: python3
    python-packages: [h2, hpack, hyper, hyperframe, requests, 'git+https://github.com/moaxey/python-zeroconf', pocketsphinx, pyaudio]
  pyalexa:
    plugin: dump
    source: ..
    organize:
      alexa.py: bin/alexa.py
      alexa_audio.py: bin/alexa_audio.py
      alexa_audio_device.py: bin/alexa_audio_device.py
      alexa_auth.py: bin/alexa_auth.py
      alexa_communication.py: bin/alexa_communication.py
      alexa_control.py: bin/alexa_control.py
      alexa_device.py: bin/alexa_device.py
      alexa_http_config.py: bin/alexa_http_config.py
      alexa_params.py: bin/alexa_params.py
    stage-packages:
      - ffmpeg
      - libpulse0
      - pavucontrol
      - pulseaudio
      - libportaudio2
    build-packages:
      - swig
      - portaudio19-dev
      - libpulse-dev
  alsa-lib:
    source: git://git.alsa-project.org/alsa-lib.git
    plugin: autotools
    configflags: [--with-configdir=/snap/alexa/current/usr/share/alsa]
    stage-packages:
      - libasound2
      - libasound2-data
    build-packages:
      - git
      - g++
      - make
      - autoconf
      - libtool
      - automake
      - build-essential

